{% set name = "tardigrade_abaqus_tools" %}
{% set version = "0.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UCBoulder/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 10071dd4291d0c09d4a8b9200753fdfb2eecf01eb3980926f181ff38d094c179

build:
  number: 1
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script:
    - set -x
    # Build and install c++ libraries
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release ${CMAKE_ARGS}
    - cmake --install build --prefix ${PREFIX}
  skip: true  # [win]

requirements:
  build:
    - python
    - {{ compiler('c') }}  # TODO: Remove when the upstream project updates the CMakeLists.txt file
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - make
    - cmake >=3.30
    - breathe >=4.3.0
    - clang-tools
    - doxygen
    - libboost-python-devel >=1.82
    - setuptools >=62
    - setuptools_scm >=6.2
    - sphinx >=3.0.4
    - sphinx_rtd_theme >=0.4.3
    - sphinxcontrib-bibtex
    - tardigrade_vector_tools >=0.8.7
  host:
    - eigen >=3.3.7
  run:
    - eigen >=3.3.7

test:
  requires:
    - {{ compiler('cxx') }}
    - make
    - cmake >=3.30
    - clang-tools
    - libboost-python-devel >=1.82
    - doxygen
    - sphinx >=3.0.4
    - tardigrade_vector_tools >=0.8.7
  source_files:
    - CMakeLists.txt
    - src/cpp/tests/CMakeLists.txt
    - src/cpp/tests/test_tardigrade_abaqus_tools.cpp
  commands:
    - set -x
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=conda-test -DCMAKE_INSTALL_LIBDIR=lib
    - cmake --build build --verbose --parallel 4
    - ctest --test-dir build --output-on-failure -R 'test_' --parallel 4

about:
  home: https://github.com/UCBoulder/tardigrade_abaqus_tools
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'A collection of tools for C++ that make interfacing with Abaqus subroutines easier and less prone to error.'
  description: |
    tardigrade_abaqus_tools A collection of tools for C++ that make interfacing with Abaqus
    subroutines easier and less prone to error.
  dev_url: https://github.com/UCBoulder/tardigrade_abaqus_tools

extra:
  recipe-maintainers:
    - NateAM
    - kbrindley
